Introduce mpbuild api to be used by octoprobe
mattytrentini/mpbuild pull request #48
Opened 2024-11-14 08:36 UTC by hmaerki

# Summary

The functionality of `mpbuild` has not changed at all.

I added a API which allows to call `mpbuild` from octoprobe.

Notable internal change: stderr/stdout:

The existing code wrote to stderr/stdout and raised SystemExit: This is unwanted for a API as octoprobe uses python logging. Therefor I refactured the code to separate the CLI code (with stderr/stdout, SystemExit) and the code which justs works silent or raises an exception.

Notable internal change: default variant:
* Before: The default variant did not exist as a variant-object
* Now: Also the default variant is a variant-object with the flag 'default_variant' set.
* Rationale: Now every micropython-build IS a variant. I could remove many `if`s.

Notable internal change: `physical_board`:
* The `Board` class got an attribute `physical_board` which allows to distinguish between 'stm32' and 'unix'.

## The API (src/mpbuild/build_api.py)
* Throws an `MpbuildException` on failure
* Interface: `def build_by_variant(variant: Variant, do_clean: bool) -> Firmware`
* Returns the firmware filename on success

## This PR was tested on:
* Linux
* Python 3.12.2
* Docker ARM: https://github.com/mattytrentini/build-micropython-arm-docker/tree/update_to_bookworm
* Docker RP2: https://github.com/hmaerki/build-micropython-rp2350riscv-docker

## Tests where added
* See `tests/README.md`.
* All tests succeed

2024-11-20 09:01 UTC, mattytrentini reviewed
I haven't finished reviewing this yet but thought I'd share what I have so far...

2024-11-21 06:20 UTC, hmaerki commented on src/mpbuild/build.py
> +    assert isinstance(variant, Variant), variant
> They seem like they should be replaced by the use of a tool like mypy?
Yes, however, as long as we do not use such a tool, 'assert' is the way to go.
In PEP484 there is a section 'non goals': https://peps.python.org/pep-0484/#non-goals. There is NO runtime type checking!

Now 'docker_build_cmd' is an external API and therefor I check first if the parameters are valid.
Keep in mind that Octoprobe may fail in may ways as it includes hardware and is very distributed. So early/good error messages will help the developer to track down problems.

Therefor I use 'assert isinstance(...)' on interfaces. And I agree that the typeinformation is redundant to to 'assert'. This is by design (PEP484).

2024-11-21 06:47 UTC, hmaerki commented on src/mpbuild/board_database.py
> +    def directory_repo(self) -> Path:
I implemented a slim Python API towards octorprobe:

```python
def build_by_variant_str(db: Database, variant_str: str, do_clean: bool) -> Firmware:
    ...
    db_variant = db.get_board(board_str).get_variant(variant_str)
    return build_by_variant(variant=db_variant, do_clean=do_clean)
```

Do you agree with this interface?

To the question is this method: `build_by_variant(variant: Variant...) -> Firmware`.

As you see, the `variant` specifies everything.

Are you fine with this signature?

If yes, we have to get the `directory_repo` from somewhere. I added it to the class port, I personally would prefer to use the class `Database`.

2024-11-21 07:08 UTC, hmaerki commented on src/mpbuild/board_database.py
> +    """
Thanks! Fixed

2024-11-21 11:54 UTC, hmaerki commented on src/mpbuild/board_database.py
> +DEFAULT_VARIANT = ""
My comment below about `def build_by_variant_str` gives some insights.

2024-11-21 12:17 UTC, hmaerki commented on src/mpbuild/board_database.py
> +    def find_variant(self, variant: str) -> Variant | None:
See my comment below about `def build_by_variant_str`

2024-12-01 06:07 UTC, mattytrentini requested changes
Broadly speaking, here are some of the features included in this PR:

* Building by variant string
  * _Must be_ by board and optional variant IMO
  * And I would prefer *no variant* to be represented by None, as it was, not an empty string (that was a conscious implementation choice on my behalf)
* Tests
  * I'm _very_ happy to see tests! But I'd strongly prefer them to run independently of requiring a MicroPython clone.
    * The general idea was to mock out the filesystem - create a fake one in the 'shape' of MicroPython
    * I'd also prefer to see them run under a test framework, probably PyTest
      * Much easier to automate
    * Not sure whether to include this or not at this stage - mostly because I don't want more contributions that extend it further.
* asserts to check type
  * IMO should be used _sparingly_ in a dynamically typed language like Python. The right solution is to use Type Hints and a type checker - which is my intent. I'd personally prefer to remove them but, if you're attached to them, then I'm ok with leaving them for now. But I do intend to remove them later. 
* `Board` changes
  * `physical_board` 
    * Good, better than my previous use of 'special build' to indicate unix/wasm/windows
  * Add `directory`
    * Good, have already used it in another PR
  * `deploy_filename`
    * Less enamored with because we have little control over what the build system does. But I'm ok with it.
  * `find_variant` and `get_variant`
    * I think should be removed. Unless there is a compelling use case?
* `Port` changes
  * `directory`
    * Yes, good addition
  * `directory_repo`
    * You've tidied this up a lot but it's still a bit of a mess which needs to be resolved. I agree with your comment that it should be in Database and would prefer to see it moved there. I think there are also remnants of `mpy_root` (?) which may need to be tidied up but I can take care of that.
* `Database` changes
  * Adding named parameters to Board init
    * Yes, good
  * `assert_mpy_root_directory`
    * Good
  * `get_board`
    * I'm in two minds: It really doesn't add much IMO.
* `get_build_container`
  * Needs to take a board and optional variant
  * FWIW, I intend to overhaul how containers are selected at some point in the future. I want it to be done in a configuration file by port, board or variant.
* Firmware
  * I'm not sure what to do with this. I don't really want it included as I think it will be a maintenance burden. Is there any way around it?

There's a lot of good stuff here - thanks very much for the contribution! - but some of it I'm not comfortable merging. The main issue is, I guess, the difference in how we specify a build; I think it should remain board and optional variant, and I want that throughout the API and interfaces.

It would also certainly have helped if this had been broken into smaller PRs! And maybe that's how we should move forward?

2024-12-03 06:01 UTC, hmaerki commented on src/mpbuild/board_database.py
> +    def deploy_filename(self) -> Path:
> No, I don't think we should build solely by variant name. 
Yes of course I agree with you. Is it possible that you didn't understand my code: A variant always belongs to a port!

2024-12-19 07:04 UTC, closed without merging